# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.BookableSlot'),
        ),
    ]
