# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_firm_org_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookableSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('price', models.IntegerField(default=40)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Firm')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='bookableslot',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Service'),
        ),
    ]
