# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-27 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180103_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookableslot',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
