# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-28 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bookableslot_isbooked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookableslot',
            name='isBooked',
        ),
    ]
